### ISSUE TITLE
Tiles mixed in with text and missing tiles on various maps

### ISSUE THREAD

**Issue by nephitejnf** [SoupPotato/Sourcrystal#9]
So far, I've seen off color spaces or spaces replaced with tiles and some tiles missing on certain maps.

This is in gambatte, the pokemon speedruns fork.

I did compile from source, off of this commit.
https://github.com/SoupPotato/Sourcrystal/commit/38173644dd49691a3a0ee0bc108bd6a7d35a2c5a

I have a couple examples of where it has happened.
https://imgur.com/a/e8WHZQR

**Comment by SoupPotato** [comment]
This is an issue of compatibility with rgbasm 4.0 and above.

Building it on a version lower than that will fix the error
